# Generated by Django 2.0.8 on 2018-10-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='photoUrl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='zipcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
