# Generated by Django 2.0.9 on 2018-10-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirapp', '0002_auto_20181001_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='photoUrl',
            new_name='photourl',
        ),
    ]
