# Generated by Django 2.0.8 on 2018-10-02 22:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirapp', '0003_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='places',
        ),
        migrations.AddField(
            model_name='trip',
            name='places',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
