# Generated by Django 2.0.8 on 2018-10-02 22:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirapp', '0005_auto_20181002_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='places',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
<<<<<<< HEAD
]
=======
    ]
>>>>>>> 4394cae3c5c1a9e6cc4353cf209153690eb71db0
