# Generated by Django 2.0.9 on 2018-10-02 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirapp', '0003_auto_20181002_1405'),
        ('souvenirapp', '0006_auto_20181002_1537'),
    ]

    operations = [
    ]
