# Generated by Django 2.0.9 on 2018-10-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirapp', '0007_merge_20181002_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
